from fastapi import APIRouter

from app.api.v1.routes import (
    alerts,
    api_keys,
    auth,
    case_statuses,
    case_templates,
    cases,
    comments,
    custom_fields,
    events,
    integrity,
    knowledge_bases,
    logs,
    metrics_dashboards,
    misp,
    notifications,
    observable_types,
    observables,
    organisations,
    overview,
    patterns,
    permissions,
    plugin_results,
    plugin_runners,
    plugins,
    proposed_actions,
    report_templates,
    roles,
    search,
    slas,
    system,
    tags,
    tasks,
    users,
    ws,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(organisations.router)
api_router.include_router(overview.router)
api_router.include_router(roles.router)
api_router.include_router(permissions.router)
api_router.include_router(tags.router)
api_router.include_router(cases.router)
api_router.include_router(case_statuses.router)
api_router.include_router(tasks.router)
api_router.include_router(tasks.queue_router)
api_router.include_router(logs.router)
api_router.include_router(alerts.router)
api_router.include_router(observables.router)
api_router.include_router(observable_types.router)
api_router.include_router(comments.router)
api_router.include_router(case_templates.router)
api_router.include_router(custom_fields.router)
api_router.include_router(events.router)
api_router.include_router(integrity.router)
api_router.include_router(api_keys.router)
api_router.include_router(slas.router)
api_router.include_router(knowledge_bases.router)
api_router.include_router(metrics_dashboards.dash_router)
api_router.include_router(metrics_dashboards.public_dash_router)
api_router.include_router(misp.router)
api_router.include_router(notifications.router)
api_router.include_router(patterns.router)
api_router.include_router(plugin_results.router)
api_router.include_router(plugin_runners.router)
api_router.include_router(plugins.router)
api_router.include_router(plugins.runs_router)
api_router.include_router(proposed_actions.router)
api_router.include_router(report_templates.router)
api_router.include_router(search.router)
api_router.include_router(system.router)
api_router.include_router(ws.router)
