"""add cases tasks logs

Revision ID: c1eeb01936c1
Revises: 929a4e949127
Create Date: 2026-06-11 23:33:47.964594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1eeb01936c1'
down_revision: Union[str, Sequence[str], None] = '929a4e949127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('tlp', sa.Integer(), nullable=False),
    sa.Column('pap', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'duplicated', name='casestatus'), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolution_status', sa.Enum('indeterminate', 'false_positive', 'true_positive', 'other', 'duplicated', name='caseresolutionstatus'), nullable=True),
    sa.Column('impact_status', sa.Enum('no_impact', 'with_impact', 'not_applicable', name='caseimpactstatus'), nullable=True),
    sa.Column('duplicate_of_case_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_case_id'], ['case_.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation_link',
    sa.Column('from_org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('case_sharing', sa.Enum('manual', 'supervised', 'notify', name='casesharingmode'), nullable=False),
    sa.Column('task_sharing', sa.Enum('manual', 'auto_share', name='autosharemode'), nullable=False),
    sa.Column('observable_sharing', sa.Enum('manual', 'auto_share', name='autosharemode'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['from_org_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_org_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_org_id', 'to_org_id')
    )
    op.create_table('case_share',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('case_id', 'organisation_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'in_progress', 'completed', 'cancelled', name='taskstatus'), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['case_.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_case_id'), 'task', ['case_id'], unique=False)
    op.create_index(op.f('ix_task_organisation_id'), 'task', ['organisation_id'], unique=False)
    op.create_table('log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_organisation_id'), 'log', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_log_task_id'), 'log', ['task_id'], unique=False)
    op.create_table('task_share',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'organisation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_share')
    op.drop_index(op.f('ix_log_task_id'), table_name='log')
    op.drop_index(op.f('ix_log_organisation_id'), table_name='log')
    op.drop_table('log')
    op.drop_index(op.f('ix_task_organisation_id'), table_name='task')
    op.drop_index(op.f('ix_task_case_id'), table_name='task')
    op.drop_table('task')
    op.drop_table('case_share')
    op.drop_table('organisation_link')
    op.drop_table('case_')
    # ### end Alembic commands ###
